package ru.yandex.bolts.function;

// this file is generated by ru.yandex.bolts.function.gen.GenerateFunctions

import ru.yandex.bolts.collection.Tuple3;


@FunctionalInterface
public interface Function3<A, B, C, R> {

    R apply(A a, B b, C c);

    default Function2<B, C, R> bind1(final A a) {
        return (b, c) -> apply(a, b, c);
    }

    default Function2<A, C, R> bind2(final B b) {
        return (a, c) -> apply(a, b, c);
    }

    default Function2<A, B, R> bind3(final C c) {
        return (a, b) -> apply(a, b, c);
    }


    static <A, B, C, R> Function2<Function3<A, B, C, R>, A, Function2<B, C, R>> bind1F2() {
        return Function3::bind1;
    }

    default Function<A, Function2<B, C, R>> bind1F() {
        return Function3.<A, B, C, R>bind1F2().bind1(this);
    }

    static <A, B, C, R> Function2<Function3<A, B, C, R>, B, Function2<A, C, R>> bind2F2() {
        return Function3::bind2;
    }

    default Function<B, Function2<A, C, R>> bind2F() {
        return Function3.<A, B, C, R>bind2F2().bind1(this);
    }

    static <A, B, C, R> Function2<Function3<A, B, C, R>, C, Function2<A, B, R>> bind3F2() {
        return Function3::bind3;
    }

    default Function<C, Function2<A, B, R>> bind3F() {
        return Function3.<A, B, C, R>bind3F2().bind1(this);
    }

    default Function<Tuple3<A, B, C>, R> asFunction() {
        return t -> apply(t._1, t._2, t._3);
    }

    @SuppressWarnings("unchecked")
    default <A1, B1, C1, R1> Function3<A1, B1, C1, R1> uncheckedCast() {
        return (Function3<A1, B1, C1, R1>) this;
    }

} //~
