package ru.yandex.bolts.function;

// this file is generated by ru.yandex.bolts.function.gen.GenerateFunctions

import ru.yandex.bolts.collection.Tuple3;

/**
 */
@FunctionalInterface
public interface Function3B<A, B, C> {

    boolean apply(A a, B b, C c);

    default Function2B<B, C> bind1(final A a) {
        return (b, c) -> apply(a, b, c);
    }

    default Function2B<A, C> bind2(final B b) {
        return (a, c) -> apply(a, b, c);
    }

    default Function2B<A, B> bind3(final C c) {
        return (a, b) -> apply(a, b, c);
    }


    static <A, B, C> Function2<Function3B<A, B, C>, A, Function2B<B, C>> bind1F2() {
        return (f, a) -> f.bind1(a);
    }

    default Function<A, Function2B<B, C>> bind1F() {
        return Function3B.<A, B, C>bind1F2().bind1(this);
    }

    static <A, B, C> Function2<Function3B<A, B, C>, B, Function2B<A, C>> bind2F2() {
        return (f, b) -> f.bind2(b);
    }

    default Function<B, Function2B<A, C>> bind2F() {
        return Function3B.<A, B, C>bind2F2().bind1(this);
    }

    static <A, B, C> Function2<Function3B<A, B, C>, C, Function2B<A, B>> bind3F2() {
        return (f, c) -> f.bind3(c);
    }

    default Function<C, Function2B<A, B>> bind3F() {
        return Function3B.<A, B, C>bind3F2().bind1(this);
    }

    default Function<Tuple3<A, B, C>, Boolean> asFunction() {
        return t -> apply(t._1, t._2, t._3);
    }

    default Function1B<Tuple3<A, B, C>> asFunction1B() {
        return t -> apply(t._1, t._2, t._3);
    }

    default Function3<A, B, C, Boolean> asFunction3() {
        return (a, b, c) -> apply(a, b, c);
    }

    @SuppressWarnings("unchecked")
    default <A1, B1, C1> Function3B<A1, B1, C1> uncheckedCast() {
        return (Function3B<A1, B1, C1>) this;
    }

} //~
