package ru.yandex.bolts.function;

// this file is generated by ru.yandex.bolts.function.gen.GenerateFunctions

import ru.yandex.bolts.collection.Tuple3;

/**
 * @see fj.F3
 */
public abstract class Function3V<A, B, C> {

    public abstract void apply(A a, B b, C c);

    public Function2V<B, C> bind1(final A a) {
        return new Function2V<B, C>() {
            public void apply(B b, C c) {
                Function3V.this.apply(a, b, c);
            }

            public String toString() {
                return Function3V.this + "(" + a + ", _, _)";
            }
        };
    }

    public Function2V<A, C> bind2(final B b) {
        return new Function2V<A, C>() {
            public void apply(A a, C c) {
                Function3V.this.apply(a, b, c);
            }

            public String toString() {
                return Function3V.this + "(_, " + b + ", _)";
            }
        };
    }

    public Function2V<A, B> bind3(final C c) {
        return new Function2V<A, B>() {
            public void apply(A a, B b) {
                Function3V.this.apply(a, b, c);
            }

            public String toString() {
                return Function3V.this + "(_, _, " + c + ")";
            }
        };
    }


    public static <A, B, C> Function2<Function3V<A, B, C>, A, Function2V<B, C>> bind1F2() {
        return new Function2<Function3V<A, B, C>, A, Function2V<B, C>>() {
            public Function2V<B, C> apply(Function3V<A, B, C> f, A a) {
                return f.bind1(a);
            }

            public String toString() {
                return "bind1";
            }
        };
    }

    public Function<A, Function2V<B, C>> bind1F() {
        return Function3V.<A, B, C>bind1F2().bind1(this);
    }

    public static <A, B, C> Function2<Function3V<A, B, C>, B, Function2V<A, C>> bind2F2() {
        return new Function2<Function3V<A, B, C>, B, Function2V<A, C>>() {
            public Function2V<A, C> apply(Function3V<A, B, C> f, B b) {
                return f.bind2(b);
            }

            public String toString() {
                return "bind2";
            }
        };
    }

    public Function<B, Function2V<A, C>> bind2F() {
        return Function3V.<A, B, C>bind2F2().bind1(this);
    }

    public static <A, B, C> Function2<Function3V<A, B, C>, C, Function2V<A, B>> bind3F2() {
        return new Function2<Function3V<A, B, C>, C, Function2V<A, B>>() {
            public Function2V<A, B> apply(Function3V<A, B, C> f, C c) {
                return f.bind3(c);
            }

            public String toString() {
                return "bind3";
            }
        };
    }

    public Function<C, Function2V<A, B>> bind3F() {
        return Function3V.<A, B, C>bind3F2().bind1(this);
    }

    public Function<Tuple3<A, B, C>, Object> asFunction() {
        return new Function<Tuple3<A, B, C>, Object>() {
            public Object apply(Tuple3<A, B, C> t) {
                Function3V.this.apply(t._1, t._2, t._3);
                return null;
            }

            public String toString() {
                return Function3V.this.toString();
            }
        };
    }

    public Function1V<Tuple3<A, B, C>> asFunction1V() {
        return new Function1V<Tuple3<A, B, C>>() {
            public void apply(Tuple3<A, B, C> t) {
                Function3V.this.apply(t._1, t._2, t._3);
            }

            public String toString() {
                return Function3V.this.toString();
            }
        };
    }

    public Function3<A, B, C, Object> asFunction3() {
        return new Function3<A, B, C, Object>() {
            public Object apply(A a, B b, C c) {
                Function3V.this.apply(a, b, c);
                return null;
            }

            public String toString() {
                return Function3V.this.toString();
            }
        };
    }

    @SuppressWarnings("unchecked")
    public <A1, B1, C1> Function3V<A1, B1, C1> uncheckedCast() {
        return (Function3V<A1, B1, C1>) this;
    }

} //~
