package ru.yandex.bolts.collection;

import java.io.Serializable;

import fj.P4;

import ru.yandex.bolts.function.Function;

/**
 * Quadruple.
 *
 * @author Stepan Koltsov
 *
 * @see Tuple2
 * @see P4
 */
public class Tuple4<T1, T2, T3, T4> implements Serializable {
    private static final long serialVersionUID = 5566029783258786962L;

    public final T1 _1;
    public final T2 _2;
    public final T3 _3;
    public final T4 _4;

    public Tuple4(T1 _1, T2 _2, T3 _3, T4 _4) {
        this._1 = _1;
        this._2 = _2;
        this._3 = _3;
        this._4 = _4;
    }

    public T1 get1() {
        return _1;
    }

    public T2 get2() {
        return _2;
    }

    public T3 get3() {
        return _3;
    }

    public T4 get4() {
        return _4;
    }

    @SuppressWarnings("unchecked")
    private <A> A get(int a) {
        switch (a) {
        case 1: return (A) _1;
        case 2: return (A) _2;
        case 3: return (A) _3;
        case 4: return (A) _4;
        default: throw new IllegalArgumentException();
        }
    }

    private <A, B> Tuple2<A, B> get(int a, int b) {
        return Tuple2.tuple(this.<A>get(a), this.<B>get(b));
    }

    private <A, B, C> Tuple3<A, B, C> get(int a, int b, int c) {
        return Tuple3.tuple(this.<A>get(a), this.<B>get(b), this.<C>get(c));
    }

    public Tuple2<T1, T2> get12() {
        return this.get(1, 2);
    }

    public Tuple2<T1, T3> get13() {
        return this.get(1, 3);
    }

    public Tuple2<T1, T4> get14() {
        return this.get(1, 4);
    }

    public Tuple2<T2, T3> get23() {
        return this.get(2, 3);
    }

    public Tuple2<T2, T4> get24() {
        return this.get(2, 4);
    }

    public Tuple2<T3, T4> get34() {
        return this.get(3, 4);
    }

    public Tuple3<T1, T2, T3> get123() {
        return this.get(1, 2, 3);
    }

    public Tuple3<T1, T2, T4> get124() {
        return this.get(1, 2, 4);
    }

    public Tuple3<T2, T3, T4> get234() {
        return this.get(2, 3, 4);
    }

    public Tuple3<T1, T3, T4> get134() {
        return this.get(1, 3, 4);
    }


    @Override
    public int hashCode() {
        // generated by Eclipse
        final int prime = 31;
        int result = 1;
        result = prime * result + ((_1 == null) ? 0 : _1.hashCode());
        result = prime * result + ((_2 == null) ? 0 : _2.hashCode());
        result = prime * result + ((_3 == null) ? 0 : _3.hashCode());
        result = prime * result + ((_4 == null) ? 0 : _4.hashCode());
        return result;
    }

    @SuppressWarnings("unchecked")
    @Override
    public boolean equals(Object obj) {
        // generated by Eclipse
        if (this == obj) return true;
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;
        Tuple4 other = (Tuple4) obj;
        if (_1 == null) {
            if (other._1 != null) return false;
        } else if (!_1.equals(other._1)) return false;
        if (_2 == null) {
            if (other._2 != null) return false;
        } else if (!_2.equals(other._2)) return false;
        if (_3 == null) {
            if (other._3 != null) return false;
        } else if (!_3.equals(other._3)) return false;
        if (_4 == null) {
            if (other._4 != null) return false;
        } else if (!_4.equals(other._4)) return false;
        return true;
    }

    @Override
    public String toString() {
        return "(" + _1 + ", " + _2 + ", " + _3 + ", " + _4 + ")";
    }

    /** @deprecated */
    public static <A, B, C, D> Function<Tuple4<A, B, C, D>, A> get1M() {
        return get1F();
    }

    public static <A, B, C, D> Function<Tuple4<A, B, C, D>, A> get1F() {
        return new Function<Tuple4<A, B, C, D>, A>() {
            public A apply(Tuple4<A, B, C, D> tuple) {
                return tuple._1;
            }
        };
    }

    public static <A, B, C, D> Function<Tuple4<A, B, C, D>, B> get2F() {
        return new Function<Tuple4<A, B, C, D>, B>() {
            public B apply(Tuple4<A, B, C, D> tuple) {
                return tuple._2;
            }
        };
    }

    public static <A, B, C, D> Function<Tuple4<A, B, C, D>, C> get3F() {
        return new Function<Tuple4<A, B, C, D>, C>() {
            public C apply(Tuple4<A, B, C, D> tuple) {
                return tuple._3;
            }
        };
    }

    public static <A, B, C, D> Function<Tuple4<A, B, C, D>, D> get4F() {
        return new Function<Tuple4<A, B, C, D>, D>() {
            public D apply(Tuple4<A, B, C, D> tuple) {
                return tuple._4;
            }
        };
    }


    /** @deprecated */
    public static <A, B, C, D, X> Function<Tuple4<A, B, C, D>, Tuple4<X, B, C, D>> map1M(final Function<A, X> m) {
        return map1F(m);
    }

    public static <A, B, C, D, X> Function<Tuple4<A, B, C, D>, Tuple4<X, B, C, D>> map1F(final Function<A, X> m) {
        return new Function<Tuple4<A, B, C, D>, Tuple4<X, B, C, D>>() {
            public Tuple4<X, B, C, D> apply(Tuple4<A, B, C, D> t) {
                return tuple(m.apply(t._1), t._2, t._3, t._4);
            }
        };
    }

    /** @deprecated */
    public static <A, B, C, D, X> Function<Tuple4<A, B, C, D>, Tuple4<A, X, C, D>> map2M(final Function<B, X> m) {
        return map2F(m);
    }

    public static <A, B, C, D, X> Function<Tuple4<A, B, C, D>, Tuple4<A, X, C, D>> map2F(final Function<B, X> m) {
        return new Function<Tuple4<A, B, C, D>, Tuple4<A, X, C, D>>() {
            public Tuple4<A, X, C, D> apply(Tuple4<A, B, C, D> t) {
                return tuple(t._1, m.apply(t._2), t._3, t._4);
            }
        };
    }

    /** @deprecated */
    public static <A, B, C, D, X> Function<Tuple4<A, B, C, D>, Tuple4<A, B, X, D>> map3M(final Function<C, X> m) {
        return map3F(m);
    }

    public static <A, B, C, D, X> Function<Tuple4<A, B, C, D>, Tuple4<A, B, X, D>> map3F(final Function<C, X> m) {
        return new Function<Tuple4<A, B, C, D>, Tuple4<A, B, X, D>>() {
            public Tuple4<A, B, X, D> apply(Tuple4<A, B, C, D> t) {
                return tuple(t._1, t._2, m.apply(t._3), t._4);
            }
        };
    }

    /** @deprecated */
    public static <A, B, C, D, X> Function<Tuple4<A, B, C, D>, Tuple4<A, B, C, X>> map4M(final Function<D, X> m) {
        return map4F(m);
    }

    public static <A, B, C, D, X> Function<Tuple4<A, B, C, D>, Tuple4<A, B, C, X>> map4F(final Function<D, X> m) {
        return new Function<Tuple4<A, B, C, D>, Tuple4<A, B, C, X>>() {
            public Tuple4<A, B, C, X> apply(Tuple4<A, B, C, D> t) {
                return tuple(t._1, t._2, t._3, m.apply(t._4));
            }
        };
    }

    public static <A, B, C, D, E> Function<E, Tuple4<A, B, C, D>> join(final Function<E, A> fa, final Function<E, B> fb, final Function<E, C> fc, final Function<E, D> fd) {
        return new Function<E, Tuple4<A, B, C, D>>() {
            public Tuple4<A, B, C, D> apply(E e) {
                return Tuple4.tuple(fa.apply(e), fb.apply(e), fc.apply(e), fd.apply(e));
            }
        };
    }

    private static <A, B, C, D, E, F> Function<Tuple4<A, B, C, D>, Tuple2<E, F>> getF(final int e, final int f) {
        return new Function<Tuple4<A, B, C, D>, Tuple2<E, F>>() {
            public Tuple2<E, F> apply(Tuple4<A, B, C, D> t) {
                return t.get(e, f);
            }

        };
    }

    private static <A, B, C, D, E, F, G> Function<Tuple4<A, B, C, D>, Tuple3<E, F, G>> getF(final int e, final int f, final int g) {
        return new Function<Tuple4<A, B, C, D>, Tuple3<E, F, G>>() {
            public Tuple3<E, F, G> apply(Tuple4<A, B, C, D> t) {
                return t.get(e, f, g);
            }
        };
    }


    public static <A, B, C, D> Function<Tuple4<A, B, C, D>, Tuple2<A, B>> get12F() {
        return getF(1, 2);
    }

    public static <A, B, C, D> Function<Tuple4<A, B, C, D>, Tuple2<A, C>> get13F() {
        return getF(1, 3);
    }

    public static <A, B, C, D> Function<Tuple4<A, B, C, D>, Tuple2<A, D>> get14F() {
        return getF(1, 4);
    }

    public static <A, B, C, D> Function<Tuple4<A, B, C, D>, Tuple2<B, C>> get23F() {
        return getF(2, 3);
    }

    public static <A, B, C, D> Function<Tuple4<A, B, C, D>, Tuple2<B, D>> get24F() {
        return getF(2, 4);
    }

    public static <A, B, C, D> Function<Tuple4<A, B, C, D>, Tuple2<C, D>> get34F() {
        return getF(3, 4);
    }


    public static <A, B, C, D> Function<Tuple4<A, B, C, D>, Tuple3<A, B, C>> get123F() {
        return getF(1, 2, 3);
    }

    public static <A, B, C, D> Function<Tuple4<A, B, C, D>, Tuple3<A, B, D>> get124F() {
        return getF(1, 2, 4);
    }

    public static <A, B, C, D> Function<Tuple4<A, B, C, D>, Tuple3<A, C, D>> get134F() {
        return getF(1, 3, 4);
    }

    public static <A, B, C, D> Function<Tuple4<A, B, C, D>, Tuple3<B, C, D>> get234F() {
        return getF(2, 3, 4);
    }


    public static <A, B, C, D> Tuple4<A, B, C, D> tuple(A a, B b, C c, D d) {
        return new Tuple4<A, B, C, D>(a, b, c, d);
    }

} //~
