package ru.yandex.bolts.collection;

import java.io.Serializable;

import ru.yandex.bolts.function.Function;

/**
 * @author Stepan Koltsov
 * 
 * @see Tuple2
 */
public class Tuple4<T1, T2, T3, T4> implements Serializable {
    private static final long serialVersionUID = 5566029783258786962L;
    
    private final T1 _1;
    private final T2 _2;
    private final T3 _3;
    private final T4 _4;
    
    public Tuple4(T1 _1, T2 _2, T3 _3, T4 _4) {
        this._1 = _1;
        this._2 = _2;
        this._3 = _3;
        this._4 = _4;
    }

    public T1 get1() {
        return _1;
    }

    public T2 get2() {
        return _2;
    }

    public T3 get3() {
        return _3;
    }

    public T4 get4() {
        return _4;
    }
    
    @Override
    public int hashCode() {
        // generated by Eclipse
        final int prime = 31;
        int result = 1;
        result = prime * result + ((_1 == null) ? 0 : _1.hashCode());
        result = prime * result + ((_2 == null) ? 0 : _2.hashCode());
        result = prime * result + ((_3 == null) ? 0 : _3.hashCode());
        result = prime * result + ((_4 == null) ? 0 : _4.hashCode());
        return result;
    }

    @SuppressWarnings("unchecked")
    @Override
    public boolean equals(Object obj) {
        // generated by Eclipse
        if (this == obj) return true;
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;
        Tuple4 other = (Tuple4) obj;
        if (_1 == null) {
            if (other._1 != null) return false;
        } else if (!_1.equals(other._1)) return false;
        if (_2 == null) {
            if (other._2 != null) return false;
        } else if (!_2.equals(other._2)) return false;
        if (_3 == null) {
            if (other._3 != null) return false;
        } else if (!_3.equals(other._3)) return false;
        if (_4 == null) {
            if (other._4 != null) return false;
        } else if (!_4.equals(other._4)) return false;
        return true;
    }

    @Override
    public String toString() {
        return "(" + _1 + ", " + _2 + ", " + _3 + ", " + _4 + ")";
    }
    
    public static <A, B, C, D> Function<Tuple4<A, B, C, D>, A> get1M() {
        return new Function<Tuple4<A, B, C, D>, A>() {
            public A apply(Tuple4<A, B, C, D> tuple) {
                return tuple._1;
            }
        };
    }

    public static <A, B, C, D> Function<Tuple4<A, B, C, D>, B> get2M() {
        return new Function<Tuple4<A, B, C, D>, B>() {
            public B apply(Tuple4<A, B, C, D> tuple) {
                return tuple._2;
            }
        };
    }

    public static <A, B, C, D> Function<Tuple4<A, B, C, D>, C> get3M() {
        return new Function<Tuple4<A, B, C, D>, C>() {
            public C apply(Tuple4<A, B, C, D> tuple) {
                return tuple._3;
            }
        };
    }
    
    public static <A, B, C, D> Function<Tuple4<A, B, C, D>, D> get4M() {
        return new Function<Tuple4<A, B, C, D>, D>() {
            public D apply(Tuple4<A, B, C, D> tuple) {
                return tuple._4;
            }
        };
    }

    
    public static <A, B, C, D, X> Function<Tuple4<A, B, C, D>, Tuple4<X, B, C, D>> map1M(final Function<A, X> m) {
        return new Function<Tuple4<A, B, C, D>, Tuple4<X, B, C, D>>() {
            public Tuple4<X, B, C, D> apply(Tuple4<A, B, C, D> t) {
                return tuple(m.apply(t._1), t._2, t._3, t._4);
            }
        };
    }

    public static <A, B, C, D, X> Function<Tuple4<A, B, C, D>, Tuple4<A, X, C, D>> map2M(final Function<B, X> m) {
        return new Function<Tuple4<A, B, C, D>, Tuple4<A, X, C, D>>() {
            public Tuple4<A, X, C, D> apply(Tuple4<A, B, C, D> t) {
                return tuple(t._1, m.apply(t._2), t._3, t._4);
            }
        };
    }

    public static <A, B, C, D, X> Function<Tuple4<A, B, C, D>, Tuple4<A, B, X, D>> map3M(final Function<C, X> m) {
        return new Function<Tuple4<A, B, C, D>, Tuple4<A, B, X, D>>() {
            public Tuple4<A, B, X, D> apply(Tuple4<A, B, C, D> t) {
                return tuple(t._1, t._2, m.apply(t._3), t._4);
            }
        };
    }

    public static <A, B, C, D, X> Function<Tuple4<A, B, C, D>, Tuple4<A, B, C, X>> map4M(final Function<D, X> m) {
        return new Function<Tuple4<A, B, C, D>, Tuple4<A, B, C, X>>() {
            public Tuple4<A, B, C, X> apply(Tuple4<A, B, C, D> t) {
                return tuple(t._1, t._2, t._3, m.apply(t._4));
            }
        };
    }


    public static <A, B, C, D> Tuple4<A, B, C, D> tuple(A a, B b, C c, D d) {
        return new Tuple4<A, B, C, D>(a, b, c, d);
    }
    
} //~
